# Generated by Django 4.1.7 on 2023-08-19 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
