# Generated by Django 4.1.7 on 2023-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=100)),
            ],
        ),
    ]
